### ISSUE TITLE
OAuth authentication: Invalid User error | missing option for role based access

### ISSUE THREAD

**Issue by monpty** [otwld/velero-ui#22]
Hi,

I am running velero and otwld/velero-ui in Kubernetes. I'd like to configure oauth authentication with Keycloak. 

This is my current deployment.yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-ui
  namespace: velero
spec:
  selector:
    matchLabels:
      name: velero-ui
  template:
    metadata:
      labels:
        name: velero-ui
    spec:
      serviceAccountName: velero-ui
      containers:
      - name: velero-ui
        image: otwld/velero-ui:0.5.0
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
        env:
          - name: LOG_LEVEL
            value: "debug"
          - name: BASIC_AUTH_ENABLED
            value: "false"
          - name: VELERO_UI_NAMESPACE
            value: "velero"
          - name: OAUTH_AUTH_ENABLED
            value: "true"
          - name: OAUTH_CLIENT_ID
            value: "velero"
          - name: OAUTH_CLIENT_SECRET
            value: "<client-secret>"
          - name: OAUTH_REDIRECT_URI
            value: "http://localhost:3333/login"
          - name: OAUTH_AUTHORIZATION_URL
            value: "https://<keycloak-url>/realms/master/protocol/openid-connect/auth"
          - name: OAUTH_USER_INFO_URL
            value: "https://<keycloak-url>/realms/master/protocol/openid-connect/userinfo"
          - name: OAUTH_TOKEN_URL
            value: "https://<keycloak-url>/realms/master/protocol/openid-connect/token"
          - name: OAUTH_OAUTH_SCOPE
            value: "openid profile email"
```

As soon as I try to log in, I get this error in the UI:

![Image](https://github.com/user-attachments/assets/d9be4708-adbe-4567-a94f-4c8d55d45756)

And this error in the velero-ui logs:
```
AuthenticationException: Invalid User
    at OauthStrategy.validate (/app/main.js:5482:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async OauthStrategy.callback [as _verify] (/app/node_modules/@nestjs/passport/dist/passport/passport.strategy.js:11:44) {
  response: 'Invalid User',
  status: 401,
  options: { cause: 'OauthStrategy' },
  cause: 'OauthStrategy',
  objectOrError: 'Invalid User'
}
{"0":"OauthStrategy","level":"error","message":"Invalid User","ms":"+102ms","timestamp":"2025-02-27 11:45:04"}
```

Based on the source code (https://github.com/otwld/velero-ui/blob/main/apps/velero-ui-api/src/app/modules/auth/strategies/oauth.strategy.ts), I found out that Velero relies only on the email, name and ID in the access token for OAuth authentication and does not check the user's roles. Is this assumption correct, and if so, is this a feature that is planned to be implemented in the future?

I have already checked my personal access token and user info, and all the values that velero-ui verifies (sub, name and email) are present and correct. I don't understand what else I need to do to gain access via OAuth.

This is how i configured my velero client in Keycloak:
* Client authentication: ON
* Authentication flow
  * Standard flow: ON
  * Direct access grants: ON

Maybe you can help me with this issue. Thanks in advance!
