### ISSUE TITLE
OAUTH via Dex IDP is not working (or I am misconfiguring)

### ISSUE THREAD

**Issue by schaze** [otwld/velero-ui#30]
Hi,
great tool! Thanks a lot, I am really happy having a simple glance at my cluster backups.

I run a cluster internal DEX idp server (https://dexidp.io/) which I use in various other deployments like ArgoCD, gitea,... without issues.
However I cannot seem to get velero-ui to work with it.

My deployment config looks like this (generated via helm and patched for the OAUTH and PASSPHRASE secrets:
```yaml
      - env:
        - name: OAUTH_AUTH_ENABLED
          value: "true"
        - name: OAUTH_NAME
          value: Local Auth
        - name: OAUTH_AUTHORIZATION_URL
          value: https://dex.local.schaz.org/auth
        - name: OAUTH_USER_INFO_URL
          value: https://dex.local.schaz.org/userinfo
        - name: OAUTH_CLIENT_ID
          value: cluster-local
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: oauth_client_secret
              name: velero-ui-credentials
        - name: AUTH_SECRET_PASSPHRASE
          valueFrom:
            secretKeyRef:
              key: pass_phrase
              name: velero-ui-credentials
        - name: OAUTH_REDIRECT_URI
          value: https://velero-ui.local.schaz.org/login
        - name: LOG_LEVEL
          value: info
        - name: VELERO_NAMESPACE
          value: backup
```

Secret, ID, urls etc are all correct and have been tripple checked.

I can click on the "Sign in with ..." button. Redirect works fine to my DEX, I enter my credentials and then I am redirected back to velero-ui which shows:  Unable to process login with external SSO.

The errors I am seeing in the backend is only:
```log
│ [Nest] 1  - 04/13/2025, 12:00:23 PM   ERROR [ExceptionsHandler] Failed to obtain access token                        │
│ InternalOAuthError: Failed to obtain access token                                                                    │
│     at OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:423:17)                   │
│     at /app/node_modules/passport-oauth2/lib/strategy.js:177:45                                                      │
│     at /app/node_modules/oauth/lib/oauth2.js:196:18                                                                  │
│     at ClientRequest.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:166:7)                                       │
│     at ClientRequest.emit (node:events:518:28)                                                                       │
│     at emitErrorEvent (node:_http_client:104:11)                                                                     │
│     at Socket.socketErrorListener (node:_http_client:518:5)                                                          │
│     at Socket.emit (node:events:518:28)                                                                              │
│     at emitErrorNT (node:internal/streams/destroy:170:8)                                                             │
│     at emitErrorCloseNT (node:internal/streams/destroy:129:3) 
```

And the follwing in the browser in the js console:
```json
{
    "message": "Request failed with status code 500",
    "name": "AxiosError",
    "stack": "Lt@https://velero-ui.local.schaz.org/assets/index-CcznfxAr.js:617:27661\nJL@https://velero-ui.local.schaz.org/assets/index-CcznfxAr.js:619:1039\nx@https://velero-ui.local.schaz.org/assets/index-CcznfxAr.js:619:5656\n",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": ["xhr", "http", "fetch"],
        "transformRequest": [null],
        "transformResponse": [null],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*"
        },
        "baseURL": "/api",
        "method": "get",
        "params": {
            "code": "a4gostnkdfs72i2l2uewmkz2u",
            "state": "46cb1709-7222-43ea-bee4-63642efe7ea4"
        },
        "signal": {},
        "url": "/auth/oauth"
    },
    "code": "ERR_BAD_RESPONSE",
    "status": 500
}
```

My dex idp has a auto discovery url (https://dex.local.schaz.org/.well-known/openid-configuration) which provides the following infos:
```json
{
  "issuer": "https://dex.local.schaz.org",
  "authorization_endpoint": "https://dex.local.schaz.org/auth",
  "token_endpoint": "https://dex.local.schaz.org/token",
  "jwks_uri": "https://dex.local.schaz.org/keys",
  "userinfo_endpoint": "https://dex.local.schaz.org/userinfo",
  "device_authorization_endpoint": "https://dex.local.schaz.org/device/code",
  "introspection_endpoint": "https://dex.local.schaz.org/token/introspect",
  "grant_types_supported": [
    "authorization_code",
    "implicit",
    "refresh_token",
    "urn:ietf:params:oauth:grant-type:device_code",
    "urn:ietf:params:oauth:grant-type:token-exchange"
  ],
  "response_types_supported": [
    "code",
    "id_token",
    "token"
  ],
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "code_challenge_methods_supported": [
    "S256",
    "plain"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "groups",
    "profile",
    "offline_access"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "claims_supported": [
    "iss",
    "sub",
    "aud",
    "iat",
    "exp",
    "email",
    "email_verified",
    "locale",
    "name",
    "preferred_username",
    "at_hash"
  ]
}
```

Any help would be appreciated!

Thanks & Brgds,
schaze
