### ISSUE TITLE
Downloading a backup

### ISSUE THREAD

**Issue by Sabst** [otwld/velero-ui#60]
Hello there,

When I click on the download icon of a backup I get redirected to http://minio-service-name.my-namespace.svc.cluster.local:9000/
This is the internal URL configured in velero (S3 url of backup storage location) to access minio.
There is no chance this URL can be accessed from the browser. This is fine and secure with velero as velero is in the cluster, not the browser.

My helm config is only:
```
configuration:
  general:
     veleroNamespace: "<my velero namespace>"
     secretPassPhrase:
       value: "<some secret>"
```
What am I missing?
